# Generated by Django 2.1.5 on 2019-02-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
